modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/Haizor/fancy-dyes/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "Haizor"
description = '''
${mod_description}
'''
#logoFile = ""

[[dependencies.fancydyes]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fancydyes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.fancydyes]]
#modId = "architectury"
#mandatory = true
#versionRange = "[9.0.8,)"
#ordering = "AFTER"
#side = "BOTH"